version: '3.9'

services:
  session-publisher:
    build: .
    environment:
      NUM_SESSIONS: 10
      SESSION_DELAY: 10
      AMQP_SERVER: rabbitmq
    depends_on:
      - rabbitmq  # Asegura que RabbitMQ esté disponible antes de iniciar el publicador

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Puerto del protocolo AMQP
      - "15672:15672"  # Puerto para la interfaz de gestión
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest