version: '3.9'

services:
  session-publisher:
    build: .
    environment:
      NUM_SESSIONS: 10
      SESSION_DELAY: 10
      AMQP_SERVER: rabbitmq
    depends_on:
      - rabbitmq  # Asegura que RabbitMQ esté disponible antes de iniciar el publicador

  session-processor:
    build: .
    environment:
      AMQP_SERVER: rabbitmq
      MONGO_SERVER: mongodb
      MONGO_DATABASE: session_data
    depends_on:
      - rabbitmq
      - mongodb  # Asegura que MongoDB esté disponible antes de iniciar el procesador

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Puerto del protocolo AMQP
      - "15672:15672"  # Puerto para la interfaz de gestión
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: session_data

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/session_data
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always

volumes:
  mongo-data:
    driver: local
