version: '3.9'

services:
  session-publisher:
    container_name: session-pub
    build: 
      context: session-sub
      dockerfile: Dockerfile
    environment:
      NUM_SESSIONS: 10
      SESSION_DELAY: 10
      AMQP_SERVER: rabbitmq
    depends_on:
      rabbitmq:  
        condition: service_healthy
    networks:
      - rabbitmq-network

  session-processor:
    container_name: session-processor
    build: 
      context: session-processor
      dockerfile: Dockerfile
    environment:
      AMQP_SERVER: rabbitmq
      MONGO_SERVER: mongodb
      MONGO_DATABASE: session_data
    depends_on:
      rabbitmq:  
        condition: service_healthy
      mongodb:
        condition: service_healthy  
    networks:
      - rabbitmq-network
      - mongodb-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: guest      
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rabbitmq-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: session_data
    healthcheck:  
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand({ ping: 1 })'"]  
      interval: 30s  
      timeout: 10s  
      retries: 5  
    networks:
      - mongodb-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/session_data
    depends_on:
      mongodb:
        condition: service_healthy  
    networks:
      - mongodb-network

volumes:
  mongo-data:
    driver: local

networks:
  rabbitmq-network:  
    name: rabbitmq-network  
    driver: bridge
  mongodb-network:  
    name: mongodb-network
    driver: bridge
